kind: TempoStack
apiVersion: tempo.grafana.com/v1alpha1
metadata:
  name: sample
spec:
  resources:
    total:
      limits:
        cpu: 2000m
        memory: 4Gi
  storage:
    secret:
      name: my-storage-secret
      type: s3
  storageSize: 256Mi
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
