apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators
spec:
  channel: preview
  installPlanApproval: Automatic
  name: openshift-pipelines-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
