# Copyright 2024 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: run-all-acc-tests
  namespace: maistra-pipelines
spec:
  steps:
  - name: run-all-test-cases
    image: quay.io/maistra/maistra-test-tool:2.1
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: acc-tests-pipeline
  namespace: maistra-pipelines
spec:
  tasks:
  - name: run-maistra-acc-tests
    taskRef:
      name: run-all-acc-tests
      kind: ClusterTask

---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: acc-tests-run
  namespace: maistra-pipelines
spec:
  serviceAccountName: pipeline
  timeout: 3h
  pipelineRef:
    name: acc-tests-pipeline
