name: Build and Push Image
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: maistra+kiali
        password: ${{ secrets.REGISTRY_PASSWORD }}
  
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
        push: true
        tags: quay.io/maistra/maistra-test-tool:latest
